# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MSU Electric Fish Lab
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  The MSU Electric Fish Laboratory is broadly interested in the origin and diversification of novel phenotypic and behavioral traits involved in animal communication signals.
  Diverse communication signals are often associated with species radiations, implying an important link between signal diversity and the speciation process.
  We explore these broad questions in mormyrid electric fish from Africa, which are ideally suited to highly integrative experimental approaches.
  In the laboratory, we perform our analyses across many levels of biological organization, from the genome to populations.
twitter_username: jasongallant
github_username: msuefishlab
minimal_mistakes_skin: default
search: true
repository: "msuefishlab/probable-octo-funicular"

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  toc_levels: 1..2

remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-17457337-5"

breadcrumbs: true

collections:
    people:
      output: true
      permalink: /:collection/:path/
    former_people:
      output: true
      permalink: /:collection/:path/
    research:
      output: true
      permalink: /:collection/:path/
    jobs:
      output: true
      permalink: /:collection/:path/
    msu_ngs:
      output: true
      permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true

  # _people
  - scope:
      path: ""
      type: people
    values:
      layout: single
      author_profile: true
